export const mockLeads = [
  {
    name: "Acme Corp",
    source: "Referral",
    salesAgent: "687ec1d4a0117393f3c3f172",
    status: "New",
    priority: "High",
    timeToClose: 30,
    tags: ["High Value", "Enterprise"],
  },
  {
    name: "Tech Solutions",
    source: "Website",
    salesAgent: "687ec1f2a0117393f3c3f17b",
    status: "Contacted",
    priority: "Medium",
    timeToClose: 45,
    tags: ["Follow-up"],
  },
  {
    name: "Global Industries",
    source: "Cold Call",
    salesAgent: "687ec1e0a0117393f3c3f175",
    status: "Qualified",
    priority: "High",
    timeToClose: 15,
    tags: ["Qualified", "High Value"],
  },
  {
    name: "StartupXYZ",
    source: "Advertisement",
    salesAgent: "687ec1d4a0117393f3c3f172",
    status: "New",
    priority: "Low",
    timeToClose: 60,
    tags: ["Startup"],
  },
  {
    name: "Innovation Labs",
    source: "Email",
    salesAgent: "687ec1e0a0117393f3c3f175",
    status: "Contacted",
    priority: "Medium",
    timeToClose: 30,
    tags: ["Innovation", "Follow-up"],
  },
  {
    name: "Future Systems",
    source: "Referral",
    salesAgent: "687ec1eaa0117393f3c3f178",
    status: "Proposal Sent",
    priority: "High",
    timeToClose: 10,
    tags: ["Proposal", "High Value"],
  },
  {
    name: "Digital Dynamics",
    source: "Website",
    salesAgent: "687ec1eaa0117393f3c3f178",
    status: "New",
    priority: "Medium",
    timeToClose: 25,
    tags: ["Digital", "New Lead"],
  },
  {
    name: "Enterprise Solutions",
    source: "Cold Call",
    salesAgent: "687ec1e0a0117393f3c3f175",
    status: "Qualified",
    priority: "High",
    timeToClose: 20,
    tags: ["Enterprise", "Qualified"],
  },
  {
    name: "CloudTech Inc",
    source: "Other",
    salesAgent: "687ec224a0117393f3c3f184",
    status: "Closed",
    priority: "Medium",
    timeToClose: 35,
    tags: ["Cloud", "Closed Won"],
    closedAt: new Date("2024-01-20"),
  },
  {
    name: "Smart Retail Corp",
    source: "Advertisement",
    salesAgent: "687ec1fda0117393f3c3f17e",
    status: "Contacted",
    priority: "Low",
    timeToClose: 50,
    tags: ["Retail", "Follow-up"],
  },
  {
    name: "Fintech Innovations",
    source: "Email",
    salesAgent: "687ec212a0117393f3c3f181",
    status: "Proposal Sent",
    priority: "High",
    timeToClose: 12,
    tags: ["Fintech", "High Value", "Proposal"],
  },
];
